---
# tasks file for ansible-haproxy

# This will generate passwords for these accounts.
- name: Check conditions
  assert:
    that:
    - haproxy_stats_password is defined

# Setup the configuration directory
- name: docker_container.conf dir
  file:
    state: directory
    path: '{{ config_hostdir }}'
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'
    recurse: no


- name: Populate config files
  template:
    src: "{{ item }}.j2"
    dest: "{{ config_hostdir }}/{{ item }}"
  loop:
    - haproxy.cfg

- name: Start haproxy container
  docker_container:
    name: '{{ container_name }}'
    env: '{{ container_env }}'
    hostname: '{{ container_hostname }}'
    image: '{{ image_name }}'
    networks: '{{ container_networks }}'
    ports: '{{ container_port_args }}'
    purge_networks: true
    state: started
    volumes: '{{ container_volumes }}'
